---
title: "Data processing of cities.txt"
author: "Cassandra Gunasekaram & Onkar Sadekar"
date: "`r Sys.Date()`"
output: pdf_document
---

*Here you can put any prior information, e.g. copyright note etc.*
#  Workspace setup
```{r markdown_setup, include=FALSE, echo=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE,         # Show code in the output (good for reproducibility)
                      error = FALSE       # Stop rendering if there are errors)
)
set.seed(100)
```

Install packages
```{r libraries, eval=FALSE}
install.packages("here")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("viridis")
```

Load packages: set warning=FALSE to hide warnings.
```{r libraries, warning=FALSE}
library(here)               # manage directories
library(dplyr)              # data manipulation
library(ggplot2)            # plots
library(viridis)            # colour palettes
```

Set directories (pathways to folders).
```{r pathways}
# where are we:
getwd()

# set directories
dir_raw <- here("data", "raw_data")
dir_processed <- here("data", "processed_data")
dir_derived <- here("data", "derived_data")
dir_code <- here("code")

# Check if results folder exists, if not, create one.
if(here("results")==FALSE){
  dir.create(here("results"))
} else{
  print("Results already exists")
}
dir_results <- here("results")
```
# Process raw file

```{r inspect_raw}
cities <- read.delim(file.path(dir_raw, "cities.txt"))
cities_vec <- cities$X39105000

# Explore
summary(cities_vec)
hist(cities_vec)

# Filter for >10000
cities_vec <- cities_vec[cities_vec > 10000]
write.csv(cities_vec, file.path(dir_processed, "cities_filtered.csv"), 
          row.names = FALSE)

```

# Derive from processed file
```{r derive_densities}
# First read file
cities_filtered <- read.csv(file.path(dir_processed, "cities_filtered.csv"))

source(file.path(dir_code, "get_logspaced_bins.R"))

bins <- get_log_bins(min(cities_filtered$x), max(cities_filtered$x), n_bins = 27)

counts <- table(cut(cities_filtered$x, breaks = bins, include.lowest = TRUE, right = FALSE))

write.csv(counts, file.path(dir_derived, "logspaced_density.csv"),
          row.names = FALSE)
```

```{r plot}
densities <- read.csv(file.path(dir_derived, "logspaced_density.csv"))
str(densities)
densities$avg_bins <- get_interval_mean(densities$Var1)

ggplot(densities, aes(x = log(avg_bins), y = log(Freq))) +
  geom_bar(stat = "identity", fill = "salmon1") +
  labs(x = "City population (log)", y = "Frequency (log)") +
  ggtitle("City populations histogram") +
  theme_classic()

```


